import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';

type HomeProps = {
  popularMovies: {
    page: number;
    results: [];
  };
};

const Home = ({ popularMovies }: HomeProps) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>Fajri Movies</h1>
        <hr />
      </header>

      <main>
        <div
          style={{
            display: 'flex',
            flexWrap: 'wrap',
            gap: 30,
            justifyContent: 'center',
          }}
        >
          {popularMovies.results.map((movie: any) => (
            <div key={movie.id} style={{ textAlign: 'center', width: 200 }}>
              <Image
                src={`https://image.tmdb.org/t/p/original${movie.poster_path}`}
                alt={movie.title}
                width={200}
                height={300}
                unoptimized
              />
              <h3>{movie.title}</h3>
            </div>
          ))}
        </div>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps = async () => {
  const popularMovies = await axios.get(
    'https://api.themoviedb.org/3/movie/popular',
    {
      params: {
        api_key: '6012ba1a3fd45515269a0855af81a2cc',
        language: 'en_US',
        page: 1,
      },
    }
  );

  console.log(popularMovies);

  return {
    props: {
      popularMovies: popularMovies.data,
    },
  };
};

export default Home;
