import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';

import FeaturedList from '../components/FeaturedList';

interface FeaturedData {
  page: number;
  results: [];
}

type HomeProps = {
  nowPlayingMovies: FeaturedData;
  popularMovies: FeaturedData;
  upcomingMovies: FeaturedData;
};

const Home = ({
  nowPlayingMovies,
  popularMovies,
  upcomingMovies,
}: HomeProps) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>Fajri Movies</h1>
        <hr />
      </header>

      <main>
        <FeaturedList title="Now Playing" data={nowPlayingMovies} />
        <FeaturedList title="Popular" data={popularMovies} />
        <FeaturedList title="Upcoming" data={upcomingMovies} />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export const getStaticProps = async () => {
  const nowPlayingMovies = await axios.get(
    'https://api.themoviedb.org/3/movie/now_playing',
    {
      params: {
        api_key: '6012ba1a3fd45515269a0855af81a2cc',
        language: 'en_US',
        page: 1,
      },
    }
  );

  const popularMovies = await axios.get(
    'https://api.themoviedb.org/3/movie/popular',
    {
      params: {
        api_key: '6012ba1a3fd45515269a0855af81a2cc',
        language: 'en_US',
        page: 1,
      },
    }
  );

  const upcomingMovies = await axios.get(
    'https://api.themoviedb.org/3/movie/upcoming',
    {
      params: {
        api_key: '6012ba1a3fd45515269a0855af81a2cc',
        language: 'en_US',
        page: 1,
      },
    }
  );

  return {
    props: {
      nowPlayingMovies: nowPlayingMovies.data,
      popularMovies: popularMovies.data,
      upcomingMovies: upcomingMovies.data,
    },
  };
};

export default Home;
